//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbRepository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Task_Parametrs = new HashSet<Task_Parametrs>();
            this.Task_Algorithm = new HashSet<Task_Algorithm>();
            this.User_TaskAlgorithm = new HashSet<User_TaskAlgorithm>();
        }
    
        public int Id_Task { get; set; }
        public int Id_SubThema { get; set; }
        public int Id_Status { get; set; }
        public string Name { get; set; }
        public string Condition { get; set; }
    
        public virtual AlgorithmStatu AlgorithmStatu { get; set; }
        public virtual SubThema SubThema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Parametrs> Task_Parametrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Algorithm> Task_Algorithm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_TaskAlgorithm> User_TaskAlgorithm { get; set; }
    }
}
