//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbRepository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_TaskAlgorithm
    {
        public int Id_Task { get; set; }
        public byte[] User_Algorithm_Code { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
